### ISSUE TITLE
Avoid direct text editing by soft keyboard

### ISSUE THREAD

**Issue by reza-dev20** [kojofosu/Quantitizer#12]
hello
How to prevent the keyboard from opening when touching text?(prevent change text by keyboard)

**Comment by kojofosu** [comment]
you want the ability to disable the edittext when you tap on it?

**Comment by reza-dev20** [comment]
> you want the ability to disable the edittext when you tap on it?

yes

**Comment by kojofosu** [comment]
@reza-dev20  so you can now call this method to enable of disable value inpu

```kotlin
 hQ.isReadOnly = true // Disable value input from keyboard. Default false
```
