### ISSUE TITLE
setQuantitizerListener Java

### ISSUE THREAD

**Issue by Shaewen-Chronicles** [kojofosu/Quantitizer#8]
Hey man,

nice library but i cant figure out how to use the Listener in an java instead of Kotlin

hope u can provide me with some sample code

**Comment by kojofosu** [comment]
horizontalQuantitizer.setQuantitizerListener(new QuantitizerListener() {
    @Override
    public void onIncrease() {

    }

    @Override
    public void onDecrease() {

    }
});

**Comment by kojofosu** [comment]
```java
HorizontalQuantitizer horizontalQuantitizer = findViewById(R.id.hq);
horizontalQuantitizer.setQuantitizerListener(new QuantitizerListener() {
    @Override
    public void onIncrease() {
      // TODO write code
    }

    @Override
    public void onDecrease() {
     // TODO write code
    }
});
```

**Comment by Shaewen-Chronicles** [comment]
Hey,

thank you for your fast response.
Now that i read the code its so obvius i think i shuld stop working for today 🤣
